// <auto-generated />
namespace NutritionWatcher.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class SeedDefaultData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SeedDefaultData));
        
        string IMigrationMetadata.Id
        {
            get { return "201912190905167_SeedDefaultData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
